-- GoldenAge_Config
-- Author: HSbF6HSO3F
-- DateCreated: 2025/7/19 9:10:53
--------------------------------------------------------------
INSERT INTO PlayerItems
    (Domain,                        CivilizationType,               LeaderType,                     Type,                                               Icon,                           Name,                                                       Description,                                                        SortIndex)
VALUES
    ('Players:Expansion2_Players',  'CIVILIZATION_EAGLE_UNION',     'LEADER_ESSEX_CV9',             'GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES', 'ICON_CIVILIZATION_EAGLE_UNION', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_DESCRIPTION',  999),
    ('Players:Expansion2_Players',  'CIVILIZATION_EAGLE_UNION',     'LEADER_GEORGIA',               'GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES', 'ICON_CIVILIZATION_EAGLE_UNION', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_DESCRIPTION',  999),
    ('Players:Expansion2_Players',  'CIVILIZATION_EAGLE_UNION',     'LEADER_NEW_JERSEY_BB62',       'GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES', 'ICON_CIVILIZATION_EAGLE_UNION', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_DESCRIPTION',  999),
    ('Players:Expansion2_Players',  'CIVILIZATION_EAGLE_UNION',     'LEADER_HELENA_CL50',           'GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES', 'ICON_CIVILIZATION_EAGLE_UNION', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_DESCRIPTION',  999),
    ('Players:Expansion2_Players',  'CIVILIZATION_EAGLE_UNION',     'LEADER_ALLEN_M_SUMNER_DD692',  'GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES', 'ICON_CIVILIZATION_EAGLE_UNION', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_DESCRIPTION',  999);